apiVersion: v1
data:
  IPYTHONDIR: /app/.ipython
  REDIS_URL: redis://redis:6379/0
  USE_DOCKER: "yes"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: django-envs--local--django
  name: django-envs--local--django
