apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../production.yml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: caddy
    spec:
      containers:
      - env:
        - name: DOMAIN_NAME
          valueFrom:
            configMapKeyRef:
              key: DOMAIN_NAME
              name: caddy-envs--production--caddy
        image: secdevops_production_caddy
        imagePullPolicy: Never
        name: caddy
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /root/.caddy
          name: production-caddy
      restartPolicy: Always
      volumes:
      - name: production-caddy
        persistentVolumeClaim:
          claimName: production-caddy
status: {}
